apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: obs-system
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.49
          ports:
            - containerPort: 16686  # UI
            - containerPort: 14250  # Model used by collector
          args:
            - "--memory.max-traces=100000"
            - "--query.base-path=/jaeger"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: obs-system
spec:
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
    - name: collector-grpc
      port: 14250
      targetPort: 14250
  selector:
    app: jaeger
  type: LoadBalancer  # For direct UI access
---
# Service specifically for collector connection
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: obs-system
spec:
  ports:
    - name: collector-grpc
      port: 14250
      targetPort: 14250
  selector:
    app: jaeger
